[package]
build = "build.rs"
links = "vte"
name = "vte-sys"
version = "0.2.0"

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
atk-sys = "^0.3.3"
bitflags = "0.4"
gdk-sys = "^0.3.3"
gio-sys = "^0.3.3"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk-sys = "^0.3.3"
libc = "0.2"
pango-sys = "^0.3.3"

[features]
v0_40 = []

[lib]
name = "vte_sys"
